App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path("register/", views.register_request, name="register"),
    path("updateInfo/", views.updateInfo, name="updateInfo"),
    path("reception/", views.reception, name="reception"),
    path("profile/", views.profile, name="profile"),
    path("gallery/", views.gallery, name="gallery"),
    path("order/", views.order, name="order"),
    path("review/", views.review, name="review"),
    path("success/", views.success, name="success"),
    path("filter/", views.filtererror, name="filtererror")
]

ArtGallery/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('App.urls')),
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

#Artist Model
class Artist(models.Model):
    ArtistID = models.AutoField(primary_key=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100,blank=True)
    country = models.CharField(max_length=100,blank=True,null=False)
    email=models.EmailField(max_length=100,blank=True)
    profile_pic = models.ImageField(default='Profile/avatar.png',upload_to='Profile')
    address = models.TextField(max_length=300,blank=True)
    phone = PhoneNumberField(blank=True,null=True)
    rating = models.FloatField(default=0)
    def __str__(self):
        return self.name

class Customer(models.Model):
    CustomerID = models.AutoField(primary_key=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100,blank=True)
    country = models.CharField(max_length=100,blank=True,null=False)
    email=models.EmailField(max_length=100,blank=True)
    profile_pic = models.ImageField(default='Profile/avatar.png',upload_to='Profile')
    address = models.TextField(max_length=300,blank=True)
    phone = PhoneNumberField(blank=True,null=True)
    def __str__(self):
        return self.name

class Art(models.Model):
    ArtID = models.AutoField(primary_key=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,blank=True)
    description = models.TextField(max_length=300)
    image_url = models.ImageField(upload_to='Art',default='Art/default.jpeg')
    type=models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    price = models.FloatField()
    payment=models.TextField()
    lifetime = models.TextField()
    rating = models.FloatField(default=0)
    sold = models.BooleanField(default=False)
    def __str__(self):
        return self.title
    
class Order(models.Model):
    OrderID = models.AutoField(primary_key=True)
    Odate = models.DateField()
    amount = models.FloatField()
    cname = models.TextField(max_length=100,default="")
    crole = models.TextField(max_length=100,default="")
    croleid = models.IntegerField(default=0)
    artId = models.ForeignKey(Art,on_delete=models.PROTECT)
    paid = models.BooleanField(default=False)
    def __str__(self):
        return self.artId.title
    
class Review(models.Model):
    ReviewID = models.AutoField(primary_key=True)
    date = models.DateField()
    rating = models.IntegerField(default=0)
    comment = models.TextField(max_length=300,default="")
    cname = models.TextField(max_length=100,default="")
    crole = models.TextField(max_length=100,default="")
    croleid = models.IntegerField(default=0)
    showRev = models.BooleanField(default=False)
    art = models.ForeignKey(Art,on_delete=models.PROTECT)
    def __str__(self):
        return self.art.title
    

App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Artist,Customer,Art,Order,Review

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class ArtistUpdateForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['name','country','email','address','phone',"profile_pic"]

class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','country','email','address','phone','profile_pic']

class ArtUpdateForm(forms.ModelForm):
    class Meta:
        model = Art
        fields = ['title','price','description','type','image_url']

class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['Odate','amount','cname','croleid','crole','artId']
    
class ReviewUpdateForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating','comment']

class ArtRatingForm(forms.ModelForm):
    class Meta:
        model = Art
        fields = ['rating']
class ArtistRatingForm(forms.ModelForm):
    class Meta:
        model = Art
        fields = ['rating']
    

class FilterArtForm(forms.Form):
    type = forms.CharField(required=False)
    rating = forms.FloatField(required=False)
    price = forms.FloatField(required=False)

App/templates/galleryclosed.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Art Gallery Page</title>
</head>
{%extends 'template.html'%}
{%load static%}
<body>
    {% block content%}
    <div>
        <img src="{% static 'IMGS/GalleryClosed.png' %}" class="w-screen h-screen" alt="HomePageBackground">
    </div> 
    <div class="absolute top-10 left-0 font-body text-white text-2xl">
        <a class="bg-orange-700 h-12 w-32 hover:bg-orange-600 block  flex items-center justify-center" href="{%url 'reception'%}"><- Back</a>
    </div>
    <div class="absolute top-0 hidden sidebar">
        <div class="flex h-screen w-screen">
            <div class="flex flex-col align-center justify-center h-[300px] w-[500px] border-2 border-black rounded-2xl py-6 m-auto gap-8 relative overflow-hidden">
                <div class="absolute top-0 w-full h-full">
                    <img src="{%static 'IMGS/CardBGFront.png'%}" class="w-full h-full"/>
                </div>
                <div class="absolute top-0 right-0 w-36 h-36 rounded-full bg-black m-3 overflow-hidden">
                    <img src="{%get_media_prefix%}{%if group == 'Artist'%}{{user.artist.profile_pic}}{%else%}{{user.customer.profile_pic}}{%endif%}" class="w-full h-full"/>
                </div>
                <div class="absolute top-0 z-10 p-5">
                    <h3 class="font-body text-orange-700 font-bold text-4xl text-left underline decoration-amber-500 underline-offset-4">{%if group == 'Artist'%}{{user.artist.name}}{%else%}{{user.customer.name}}{%endif%}</h3>
                    <p class="mx-auto text-xl text-left font-semibold px-3 py-6 font-body">To Create A Work Of Art Is To<br><span class="text-orange-700 text-2xl">Create A World</span></p>
                    <div class="flex flex-row w-full h-12 text-xl font-bold text-white">
                        <a href="{% url 'logout' %}" class="mx-auto bg-orange-600 hover:bg-orange-700 rounded-md flex items-center justify-center w-1/3">Logout</a>
                        <a href="{% url 'index' %}" class="mx-auto bg-orange-600 hover:bg-orange-700 rounded-md flex items-center justify-center w-1/3">Home</a>
                    </div>
                </div>
                <div class="absolute bottom-0 right-0 text-orange-700 m-8 font-heading text-2xl">
                    Art Gallery
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

App/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Art Gallery Login Page</title>
</head>
{%extends 'template.html'%}
{%load static%}
<body>
    {%block content%}
    <div class="flex flex-wrap w-full h-screen bg-orange-700 overflow-hidden font-space">
        <div class="text-center m-auto bg-white w-2/3 h-[500px] rounded-xl flex flex-row overflow-hidden">
            <div class="w-1/2 h-full hidden md:block">
                <img src="{%static 'IMGS/LoginPage.jpg'%}" alt="LoginPageIMG" class="w-full h-full"/>
            </div>
            <div class="my-auto w-1/2">
                <form action="" method="POST" class="px-20">
                    <h1 class="font-heading text-4xl md:text-5xl lg:text-7xl leading-[80px] text-center text-orange-600 mb-[20px]">Login</h1>
                    {% csrf_token %}
                    <div class="mb-[2rem] mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md" placeholder="Username" type="text" name="username" id="id_username" autofocus required>
                    </div>
                    <div class="mb-[2rem] mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md" placeholder="Password" type="password" name="password" autocomplete="new-password" required id="password">
                    </div>
                    <h5 class="my-[1rem] text-orange-700 text-left px-6">Not a User?</h5>
                    <div class="flex flex-row gap-16 w-full justify-center">
                        <button type="button" class="h-12 w-1/3 px-5 bg-orange-600 hover:bg-orange-700 rounded-md"><a class="font-body text-white text-xl" href="/register/">Register</a></button>
                        <input type="submit" class="h-12 w-1/3 px-5 bg-orange-600 hover:bg-orange-700 font-body text-white text-xl rounded-md">
                    </div>
                </form>
                <div class="my-5">
                {% for message in messages %}
                    <p class="mx-auto w-[280px] md:w-[320px] text-orange-700 font-body bg-[#f0f8ff5c] rounded-lg p-[10px]">{{message}}</p>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>   
    {%endblock%} 
</body>
</html>

App/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Art Gallery Profile</title>
</head>
{%extends 'template.html'%}
{%load static%}
<body>
    {%block content%}
    <div>
        <img src="{% static 'IMGS/paper.jpg' %}" class="w-screen h-screen" alt="ProfilePageBackground">
    </div>
    <div class="absolute top-0 w-screen">
        <h1 class="font-heading text-7xl text-center my-10 w-full mx-auto">Profile Page</h1>
        <div class="flex flex-col mx-10 font-body text-2xl">
            <div class="flex  w-1/2 m-4">
                <label for="id_name" class="w-1/2">Username:</label> 
                <p >{{user.username}}</p>
            </div>
            <div class="flex  w-1/2 m-4">
                <label for="id_name" class="w-1/2">Name:</label> 
                <p >{% if group == 'Artist' %}{{user.artist.name}}{% else %}{{user.customer.name}}{% endif %}</p>
            </div>
            <div class="flex  w-1/2 m-4">
                <label for="id_about" class="w-1/2">Address:</label>
                <p >{% if group == 'Artist' %}{{user.artist.address}}{% else %}{{user.customer.address}}{% endif %}</p>
            </div>
            <div class="flex  w-1/2 m-4">
                <label for="id_location" class="w-1/2">Country:</label>
                <p >{% if group == 'Artist' %}{{user.artist.country}}{% else %}{{user.customer.country}}{% endif %}</p>
            </div>
            <div class="flex  w-1/2 m-4 ">
                <label for="id_city" class="w-1/2" >Email:</label>
                <p>{% if group == 'Artist' %}{{user.artist.email}}{% else %}{{user.customer.email}}{% endif %}</p>
            </div>
            <div class="flex  w-1/2 m-4">
                <label for="id_phone" class="w-1/2">Phone No:</label>
                <p >{% if group == 'Artist' %}{{user.artist.phone}}{% else %}{{user.customer.phone}}{% endif %}</p>
            </div>
            {% if group == 'Artist' %}
            <div class="flex  w-1/2 m-4">
                <label for="id_state" class="w-1/2">Rating:</label>
                <div class="flex flex-row gap-1">
                    {%for star in range %}
                        {%if star <= user.artist.rating%}
                            <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" class="fill-amber-500"><path d="M6.575 20.95 8 14.8l-4.775-4.15 6.3-.55L12 4.275l2.475 5.825 6.3.55L16 14.8l1.425 6.15L12 17.7Z"/></svg>
                        {%else%}
                            <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" class="fill-gray-600"><path d="m8.85 17.825 3.15-1.9 3.15 1.925-.825-3.6 2.775-2.4-3.65-.325-1.45-3.4-1.45 3.375-3.65.325 2.775 2.425ZM6.575 20.95 8 14.8l-4.775-4.15 6.3-.55L12 4.275l2.475 5.825 6.3.55L16 14.8l1.425 6.15L12 17.7ZM12 13.25Z"/></svg>
                        {%endif%}
                    {%endfor%}
                <p>({{user.artist.rating}})</p>
                </div>
            </div>
            {% endif %}
            <button class="bg-orange-600 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-md my-4 w-1/2 EditProfileModal">Edit Profile</button>
        </div>
    </div>
    <div class="absolute right-40 top-20 w-64 h-64 rounded-full">
        <img src="{%get_media_prefix%}{% if group == 'Artist' %}{{user.artist.profile_pic}}{% else %}{{user.customer.profile_pic}}{% endif %}" class="w-full h-full rounded-full hover:scale-105 transition" alt="ProfilePic">
    </div>
    <div class="absolute top-10 left-0 font-body text-white text-2xl">
        <a class="bg-orange-700 h-12 w-32 hover:bg-orange-600 block  flex items-center justify-center" href="{%url 'reception'%}"><- Back</a>
    </div>
    <div class="hidden absolute w-screen bg-transparent backdrop-blur-sm h-screen top-0 z-50" id="ProfileModal">
        <div class="flex w-full h-full">
            <div class=" w-1/2 h-fit bg-white m-auto rounded-xl border border-black relative">
                <h3 class="text-5xl font-heading text-center my-5">Edit Profile</h3>
                <button class="EditProfileModal absolute top-5 right-10 text-4xl">&times;</button>
                <form enctype="multipart/form-data" method="POST" class="text-xl flex flex-col gap-2 items-center justify-center px-10 py-5 font-body">
                    {% csrf_token %}
                    <div class="flex flex-row gap-2 w-full">
                        <label for="uname" class="w-1/2">Username:</label>
                        <input type="text" id="uname" name="uname" class="w-full indent-4 font-body h-10 border border-gray-400 rounded-md" placeholder="{{user.username}}"><br>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="name" class="w-1/2">Name:</label>
                        <input type="text" id="name" name="name" class="w-full indent-4 font-body h-10 border border-gray-400 rounded-md" placeholder="{% if group == 'Artist' %}{{user.artist.name}}{% else %}{{user.customer.name}}{% endif %}"><br>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="address" class="w-1/2">Address:</label>
                        <textarea name="address" id="address" class="w-full indent-4 font-body h-32 border border-gray-400 rounded-md resize-none py-2" placeholder="{% if group == 'Artist' %}{{user.artist.address}}{% else %}{{user.customer.address}}{% endif %}" class="w-full"></textarea>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="country" class="w-1/2">Country:</label>
                        <select name="country" class="w-full indent-4 font-body h-10 border border-gray-400 rounded-md" id="id_country">
                            <option value="" selected hidden disabled>Choose A Country</option>
                            {% for country in countries %}
                                {%if country == user.artist.country or country == user.customer.country%}
                                    <option value="{{country}}" selected>{{country}}</option>
                                {%else%}
                                    <option value="{{country}}">{{country}}</option>
                                {%endif%}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="email" class="w-1/2">Email:</label>
                        <input type="text" id="email" name="email" class="w-full indent-4 font-body h-10 border border-gray-400 rounded-md" placeholder="{% if group == 'Artist' %}{{user.artist.email}}{% else %}{{user.customer.email}}{% endif %}"><br>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="phone" class="w-1/2">Phone No:</label>
                        <input type="text" id="phone" name="phone" class="w-full indent-4 font-body h-10 border border-gray-400 rounded-md" placeholder="{% if group == 'Artist' %}{{user.artist.phone}}{% else %}{{user.customer.phone}}{% endif %}"><br>
                    </div>
                    <div class="flex flex-row gap-2 w-full">
                        <label for="profile_pic" class="w-1/2">Profile Pic:</label>
                        <input type="file" id="profile_pic" name="profile_pic" class="w-full"><br>
                    </div>
                    <button type="submit" class="mx-auto bg-orange-600 hover:bg-orange-700 rounded-md flex items-center justify-center w-1/3 h-12 text-white font-body font-semibold text-xl">Save Profile</button>
                </form>
            </div>
        </div>
    </div>
    <div class="absolute bottom-14 right-20 flex flex-col align-center justify-center h-[300px] w-[500px] bg-gray-300 border-2 border-black rounded-2xl py-6 gap-8 -rotate-12 hover:-rotate-3 delay-75 transition-all ease-linear overflow-hidden">
        <div class="absolute top-0 w-full h-full">
            <img src="{%static 'IMGS/CardBGFront.png'%}" class="w-full h-full"/>
        </div>
        <div class="absolute top-0 right-0 w-36 h-36 rounded-full bg-black m-3 overflow-hidden">
            <img src="{%get_media_prefix%}{%if group == 'Artist'%}{{user.artist.profile_pic}}{%else%}{{user.customer.profile_pic}}{%endif%}" class="w-full h-full"/>
        </div>
        <div class="absolute top-0 z-10 p-5">
            <h3 class="font-body text-orange-700 font-bold text-4xl text-left underline decoration-amber-500 underline-offset-4">{%if group == 'Artist'%}{{user.artist.name}}{%else%}{{user.customer.name}}{%endif%}</h3>
            <p class="mx-auto text-xl text-left font-semibold px-3 py-6 font-body">To Create A Work Of Art Is To<br><span class="text-orange-700 text-2xl">Create A World</span></p>
            <div class="flex flex-row w-full h-12 text-xl font-bold text-white">
                <a href="{% url 'logout' %}" class="mx-auto bg-orange-600 hover:bg-orange-700 rounded-md flex items-center justify-center w-1/3">Logout</a>
                <a href="{% url 'index' %}" class="mx-auto bg-orange-600 hover:bg-orange-700 rounded-md flex items-center justify-center w-1/3">Home</a>
            </div>
        </div>
        <div class="absolute bottom-0 right-0 text-orange-700 m-8 font-heading text-2xl">
            Art Gallery
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $(".EditProfileModal").click(function(){
                $("#ProfileModal").toggleClass('hidden');
            });
        });
    </script>
    {%endblock%}
</body>
</html>

App/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Art Gallery Register Page</title>
</head>
{%extends 'template.html'%}
{%load static%}
<body>
    {%block content%}
    <div>
        <div class="flex flex-wrap w-full min-h-screen bg-indigo-900 overflow-hidden font-body">
            <div class="text-center m-auto bg-white w-2/3 h-[500px] rounded-xl flex flex-row overflow-hidden">
              <div class="w-1/2 h-full hidden md:block">
                <img src="{%static 'IMGS/RegisterPage.jpg'%}" alt="RegisterPageIMG" class="w-full h-full"/>
              </div>
              <div class="my-auto w-1/2">
                <form action="" method="POST" class="px-10 py-5">
                  <h1 class="font-heading text-5xl text-center text-violet-800 mb-[20px]">Register</h1>
                  {% csrf_token %}
                  <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md text-violet-800" placeholder="Email" type="email" name="email" id="id_email" required maxlength="254">
                  </div>
                  <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md text-violet-800" placeholder="Username" type="text" name="username" id="id_username" autofocus required maxlength="150">
                  </div>
                  <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    <select class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md text-violet-800" name="group" id="id_group">
                      <option value="" selected disabled hidden>Choose Your Role</option>
                      <option value="1">Artist</option>
                      <option value="2">Customer</option>
                    </select>
                  </div>
                  <div class=" mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md text-violet-800" placeholder="Password" type="password" name="password1" autocomplete="new-password" required id="id_password1">
                  </div>
                  <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    <input class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md text-violet-800" placeholder="Confirm Password" type="password" name="password2" autocomplete="new-password" required id_password2>
                  </div>
                  <h5 class="text-violet-800 text-left px-6 mb-2">Already a User?</h5>
                  <div class="flex flex-row gap-16 w-full justify-center">
                    <button type="button" class="h-12 w-1/3 px-5 bg-violet-800 hover:bg-violet-700 rounded-md"><a class="font-body text-white text-xl" href="{%url 'login'%}">Login</a></button>
                    <input type="submit" class="h-12 w-1/3 px-5 bg-violet-800 hover:bg-violet-700 font-body text-white text-xl rounded-md">
                  </div>
                  {%if form.errors%}
                    <div class="mx-auto w-[280px] md:w-[320px] text-violet-800 bg-[#f0f8ff5c] rounded-lg p-[10px]">
                      {{form.errors}}
                    </div>
                  {%endif%}
                </form>
                {% for message in messages %}
                  <div class="mx-auto w-[280px] md:w-[320px] text-violet-800 bg-[#f0f8ff5c] rounded-lg p-[10px]">
                    {{message}}
                  </div>
                {% endfor %}
              </div>
            </div>
        </div>  
    </div>
    {%endblock%}
</body>
</html>

App/templates/updateInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Info</title>
</head>
{%extends 'template.html'%}
{%load static%}
<body>
    {%block content%}
    <div class="flex p-10 flex-col w-full justify-center items-center min-h-screen bg-orange-700 overflow-hidden font-space">
        <h1 class="font-space font-heading text-4xl md:text-5xl lg:text-7xl leading-[80px] text-center text-white mb-[20px]">Welcome Aesthete</h1>
        <div class="text-center m-auto bg-white w-2/3 h-[550px] rounded-xl flex flex-row overflow-hidden">  
            <div class="w-1/2 h-full">
                <img src="{% static 'IMGS/UpdateInfo.jpg' %}" alt="Update Info" class="w-full h-full object-cover">
            </div>
            <div class="p-5 w-1/2 h-full">
                <h3 class="font-body font-bold text-2xl text-orange-700 mb-5">Please Fill In Your Information</h3>
                <form enctype="multipart/form-data" method="POST" class="flex flex-col gap-3 text-orange-700">
                    {% csrf_token %}
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input type="text" name="name" class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md" placeholder="Name" maxlength="100" id="id_name">
                    </div>
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input type="email" name="email" class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md"  placeholder="Email" maxlength="100" id="id_email">
                    </div>
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <select name="country" class="w-full indent-4 font-body h-10 border border-gray-300 rounded-md" id="id_country">
                            <option value="" selected hidden disabled>Choose A Country</option>
                            {% for country in countries %}
                                <option value="{{country}}" class="w-fit">{{country}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <textarea name="address" class="w-full indent-4 font-body h-32 border border-gray-300 rounded-md resize-none py-2"  placeholder="Address" maxlength="300" id="id_address"></textarea>
                    </div>
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input type="tel" name="phone" class="w-full indent-4 h-10 font-body border border-gray-300 rounded-md"  placeholder="Phone" maxlength="128" id="id_phone">
                    </div>
                    <div class="mx-auto w-[280px] md:w-[320px] bg-[#f0f8ff5c] rounded-lg">
                        <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
                    </div>
                    <div>
                        <input type="submit" class="h-12 w-1/3 px-5 bg-orange-600 hover:bg-orange-700 font-body text-white text-xl rounded-md">
                    </div>
                </form>
            </div>
        </div>
    </div>  
    {%endblock%}  
</body>
</html>